//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_DISEÑO
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuestionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cuestionario()
        {
            this.bloque = new HashSet<bloque>();
            this.competenciacuestionario = new HashSet<competenciacuestionario>();
        }
    
        public int IdCuestionario { get; set; }
        public string EstadoDeAprobacion { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaFin { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public int Resultado { get; set; }
        public int CantidadAccesos { get; set; }
        public System.DateTime UltimoIngreso { get; set; }
        public int PlazoParaSerContestado { get; set; }
        public int IdUsuario { get; set; }
        public int IdEvaluacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bloque> bloque { get; set; }
        public virtual candidato candidato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<competenciacuestionario> competenciacuestionario { get; set; }
    }
}
