//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_DISEÑO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CapitalHumano2Entities : DbContext
    {
        public CapitalHumano2Entities()
            : base("name=CapitalHumano2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bloque> bloque { get; set; }
        public virtual DbSet<candidato> candidato { get; set; }
        public virtual DbSet<competencia> competencia { get; set; }
        public virtual DbSet<competenciacuestionario> competenciacuestionario { get; set; }
        public virtual DbSet<consultor> consultor { get; set; }
        public virtual DbSet<cuestionario> cuestionario { get; set; }
        public virtual DbSet<empresa> empresa { get; set; }
        public virtual DbSet<estado> estado { get; set; }
        public virtual DbSet<estadodeaprobacion> estadodeaprobacion { get; set; }
        public virtual DbSet<evaluacion> evaluacion { get; set; }
        public virtual DbSet<factor> factor { get; set; }
        public virtual DbSet<factorcuestionario> factorcuestionario { get; set; }
        public virtual DbSet<itemrespuesta> itemrespuesta { get; set; }
        public virtual DbSet<itemrespuestapregunta> itemrespuestapregunta { get; set; }
        public virtual DbSet<opcionrespuesta> opcionrespuesta { get; set; }
        public virtual DbSet<pregunta> pregunta { get; set; }
        public virtual DbSet<preguntacuestionario> preguntacuestionario { get; set; }
        public virtual DbSet<puestobuscado> puestobuscado { get; set; }
        public virtual DbSet<puestobuscadocompetencia> puestobuscadocompetencia { get; set; }
        public virtual DbSet<respuestacuestionario> respuestacuestionario { get; set; }
        public virtual DbSet<tipocompetencia> tipocompetencia { get; set; }
        public virtual DbSet<tipodocumento> tipodocumento { get; set; }
    }
}
