//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_DISEÑO
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemrespuestapregunta
    {
        public int IdItemRespuesta { get; set; }
        public int IdPregunta { get; set; }
        public int PonderacionRespuesta { get; set; }
    
        public virtual itemrespuesta itemrespuesta { get; set; }
        public virtual pregunta pregunta { get; set; }
    }
}
