//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_DISEÑO
{
    using System;
    using System.Collections.Generic;
    
    public partial class preguntacuestionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public preguntacuestionario()
        {
            this.respuestacuestionario = new HashSet<respuestacuestionario>();
        }
    
        public int IdPreguntaCuestionario { get; set; }
        public int OrdenPregunta { get; set; }
        public string TextoPregunta { get; set; }
        public int IdFactorCuestionario { get; set; }
        public int IdBloque { get; set; }
    
        public virtual bloque bloque { get; set; }
        public virtual factorcuestionario factorcuestionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<respuestacuestionario> respuestacuestionario { get; set; }
    }
}
