//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_DISEÑO
{
    using System;
    using System.Collections.Generic;
    
    public partial class puestobuscadocompetencia
    {
        public int IdPuesto { get; set; }
        public int IdCompetencia { get; set; }
        public int PuntajeMinimo { get; set; }
    
        public virtual competencia competencia { get; set; }
        public virtual puestobuscado puestobuscado { get; set; }
    }
}
