//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_DISEÑO
{
    using System;
    using System.Collections.Generic;
    
    public partial class respuestacuestionario
    {
        public int IdRespuestaCuestionario { get; set; }
        public int OrdenRespuesta { get; set; }
        public string Descripción { get; set; }
        public int RespuestaSeleccionada { get; set; }
        public double Ponderación { get; set; }
        public int IdPreguntaCuestionario { get; set; }
    
        public virtual preguntacuestionario preguntacuestionario { get; set; }
    }
}
