//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_DISEÑO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipocompetencia
    {
        public int IdTipoCompetencia { get; set; }
        public string TipoCompetencia1 { get; set; }
    }
}
